# Generated by Django 4.2 on 2023-04-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='ancestors',
            new_name='relatives',
        ),
        migrations.AlterField(
            model_name='relations',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='menu.node'),
        ),
    ]
